### ISSUE TITLE
Issue launching my Lambda "cannot import name '_psutil_linux'"

### ISSUE THREAD

**Issue by laurrentt** [Netflix-Skunkworks/raven-python-lambda#35]
I'm using a laptop running macOS to deploy my serverless project. I'm trying to get the raven-python-lambda library working but it fails as soon as my lambda is launched with the following log:
```
Unable to import module 'src.***': cannot import name '_psutil_linux'
```
I think it's because it needs to be pip installed from a linux host to work properly on AWS Lambda. Is my assumption correct? Is there a workaround?

**Comment by mikegrima** [comment]
Hello!  Yes this is an issue because `psutil` uses C libraries. 

There are some ways around this but are somewhat painful depending on how you are deploying your lambda.

The TL;DR is to build your Lambda inside of an Amazon Linux docker, and find a way to grab out the  built ZIP -- OR -- send us a PR to remove psutil with something equivalent that doesn't require the C libraries. 

If you make use of Serverless, there is a plugin for it named `serverless-python-requirements` that has a `dockerizePip` flag that will build your lambda inside of an Amazon Linux docker container. This will solve the issue (if you use serverless).

**Comment by laurrentt** [comment]
‘dockerizePip’ worked like a charm! Thanks for the tip!
